# -*- coding: utf-8 -*-
"""anomaly_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4StCNecTr_VGLMIxJlv9s2mf41JWXfP
"""

import pandas as pd
from numpy import quantile

from sklearn.svm import OneClassSVM
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

df= pd.read_csv('dataset.csv',usecols=["timestamp","Google"])

df

df.dropna(inplace=True)
display(df)

df.info()

df["timestamp"]=df["timestamp"].map(lambda time:f"{time.split(':')[0]}:00:00")
df

df["timestamp"]=pd.to_datetime(df["timestamp"])
df

df.isna().sum()

df=df.groupby(by="timestamp",as_index=False).sum()
df

def graph(
    method:str,dataframe,x_col:str, y_col: str,anomaly_col:str="anomaly"
):
  fig=px.scatter(data_frame=dataframe,x=x_col,y=y_col,color=anomaly_col)
  fig.update_layout(title=f"Anomaly Detection for {company} using {method}")
  fig.show()

company = "Google"
onesvmdf=df[[company]].copy()
osvm=OneClassSVM(nu=0.2)
osvm.fit(onesvmdf)

pred=osvm.predict(onesvmdf)
pred=["normal" if value==1 else "anomaly" for value in pred]
onesvmdf["timestamp"]=df["timestamp"]
onesvmdf["anomaly"]=pred

graph(method="OneClassSVM",dataframe=onesvmdf, x_col="timestamp",y_col=company,anomaly_col="anomaly")